### ISSUE TITLE
Unable to tx

### ISSUE THREAD

**Issue by TomF8COD** [sh123/lora_arduino_kiss_modem#1]
Hello, I've finaly had some time to play with this code, but there is something I don't understand, I can't get the lora module to tx, using the lora32 or the t-beam. It's weird, I've checked that the pins are correct, the tnc decodes the lora frames from the esp32-loraprs version, but I didn't manage to make it transmit. I've tried using it on linux with Xastir, configured as a serial kiss tnc or configured as a ax25 interface. The same linux tx perfectly when I'm using the esp32-loraprs connected in bluetooth. 
Do you have any idea of what I should check ?

**Comment by sh123** [comment]
@TomF8COD , just make `git pull`, there was a typo, I believe it should work now.

**Comment by TomF8COD** [comment]
It's working ! Thank you very much.

**Comment by sh123** [comment]
@TomF8COD , the only thing is that I'm not sure how well it will perform on heavy traffic. With esp32_loraprs there are additional circular buffers utilized, so it performs well enough even if serial<->lora bandwidth do not match in any combination, which is important for stream mode, such as Codec2 traffic.

**Comment by TomF8COD** [comment]
I'm going to run it at home, I'll tell you if there's anything I see.
